version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 7
    commit-message:
      prefix: "[deps-gh]: "
      
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 7
    commit-message:
      prefix: "[deps-pip]: "
